---
title: "HW3"
author: "Amber Day"
output: html_document
---
```{r}
#rm(list=ls())
```


Read in data, load packages
```{r setup, include=FALSE}
set.seed(702)
require(ggplot2)
require(mvtnorm)
require(progress)
require(fields)
require(bayestestR)

data = read.csv("https://raw.githubusercontent.com/jgscott/SDS383D/master/data/greenbuildings.csv")
attach(data)
```

```{r}
M = 5000 #iterations
n = dim(data)[1] #7820 rows 16 columns

#Response variable = revenue per sq ft = rent*leasing rate/100
y = data$Rent*data$leasing_rate/100

#Design Matrix w/ predictors: city Market Rent, age, class a, class b
X = cbind(rep(1,n), green_rating,City_Market_Rent,age,class_a)

#Prior Initialization 
p = dim(X)[2] #7820 rows 16 columns
K = rep(0.001,p) #
K = diag(K) #prior precision matrix
m = rep(1,p)
d = 1
eta = 1
h = 1

#Initial values
lambda.vec = rgamma(n, h/2, h/2)
omega = rgamma(1, d/2, eta/2)
beta = rmvnorm(1, m, solve(omega*K))

#Save matrices
lambda.save = matrix(0,n,M)
lambda.save[,1] = lambda.vec
omega.save = rep(0,M)
omega.save[1] = omega
beta.save = matrix(0, p, M)
beta.save[,1] = beta

nu.star = n+d
eta.star = eta + t(y)%*%(lambda.vec%d*%y) + t(m)%*%K%*%m - (t(y)%*%(lambda.vec%d*%X) + t(m)%*%K)%*%solve(t(X)%*%(lambda.vec%d*%X) + K)%*%t(t(y)%*%(lambda.vec%d*%X) + t(m)%*%K)

#Progress Bar
pb = progress_bar$new(format = "Progress [:bar] :percent eta: :eta", total = M, clear = FALSE)

omega.lambda = matrix(0, n, M)
```


```{r}
#Gibbs Sampler
for(i in 2:M){
    
    pb$tick() #update progress bar

    #Sample beta

    tmp.Sig = solve(omega.save[i-1]*t(X)%*%(lambda.vec%d*%X) + omega.save[i-1]*K)
    tmp.mn = tmp.Sig%*%(omega.save[i-1]*t(X)%*%(lambda.vec%d*%y) + omega.save[i-1]*K%*%m)
    beta.save[, i] = rmvnorm(1, tmp.mn, tmp.Sig)

    #Sample omega

    omega.save[i] = rgamma(1, nu.star/2, rate = eta.star/2)

    #Sample lambda_i

    for(j in 1:n){
        lambda.save[j, i] = rgamma(1, (h+1)/2, rate = (omega.save[i]*(y[i] - X[i, ]%*%beta.save[, i])^2 + h)/2)
    }

    #New computations
    lambda.vec = lambda.save[, i]
    eta.star = eta + t(y)%*%(lambda.vec%d*%y) + t(m)%*%K%*%m - (t(y)%*%(lambda.vec%d*%X) + t(m)%*%K)%*%solve(t(X)%*%(lambda.vec%d*%X) + K)%*%t(t(y)%*%(lambda.vec%d*%X) + t(m)%*%K)

    omega.lambda[, i] = omega.save[i]*lambda.save[, i]
}

#Plot
post.means = apply(lambda.save, 1, mean)
df = data.frame(cbind(y, post = 1/post.means))
ggplot(df, aes(x = y, y = post)) + geom_point(alpha = 0.15, colour = 'blue') + ggtitle("Relative Variance for Each Data Point") + ylab("1/lambda_i")
```


```{r}
#Compare 95% CIs
set.seed(702)

#Structure Data
data.r = read.csv("https://raw.githubusercontent.com/jgscott/SDS383D/master/data/greenbuildings.csv")
n.r = dim(data)[1]

#Response  =  revenue*ft^2/100
y.r = data$Rent*data$leasing_rate/100

#design matrix
X.r = cbind(rep(1, n.r), data$green_rating, data$City_Market_Rent, data$age, data$class_a,  data$class_b) 
p.r = dim(X.r)[2] # number of parameters

#Initializations

#Priors
K.r = rep(0.001, p.r)
K.r = diag(K.r)
m.r = rep(1, p.r)
d.r = 1
eta.r = 1
Lambda.r = diag(n.r)

#Computations Using (c)
nu.star.r = n.r + d.r
Lambda.star.r = t(X.r)%*%Lambda.r%*%X.r + K.r
mu.star.r = solve(Lambda.star.r)%*%(t(X.r)%*%Lambda.r%*%y.r + t(K.r)%*%m.r)
eta.star.r = eta.r + t(y.r)%*%Lambda.r%*%y.r + t(m.r)%*%K.r%*%m.r - (t(y.r)%*%Lambda.r%*%X.r + t(m.r)%*%K.r)%*%solve(t(X.r)%*%Lambda.r%*%X.r + K.r)%*%t(t(y.r)%*%Lambda.r%*%X.r + t(m.r)%*%K.r)
Sigma.star.r = drop(eta.star.r/nu.star.r)*solve(Lambda.star.r)

#Beta updates

betas.r = rmvt(n = 1000, sigma = Sigma.star.r, df = nu.star.r, delta = mu.star.r)
```


```{r}
#Obtain 95% Intervals
#Using our method
ci(betas.r[, 2], method = "HDI")

#Using lm() method
fit = lm(y.r ~ 0 + X.r)
confint(fit)[2, ]

#Residual Analysis
res = y.r - X.r%*%apply(betas.r, 2, mean)
hist(res, main = "Histogram of Model Residuals", breaks = 50, col = "blue", border = "white")
```


```{r}
#Compare CIs
for(i in 1:5){
    cat(paste("Old Model with beta", i, ": "))
    print(ci(betas.r[, i], method = "HDI"))
    cat("\n")
    cat(paste("New Model with beta", i, ": "))
    print(ci(beta.save[i, ], method = "HDI"))
    cat("\n", "\n")
}

#Residual Analysis Comparison

res.old = y.r - X.r%*%apply(betas.r, 2, mean)
res.new = y - X%*%apply(beta.save, 1, mean)

hist(res.old, main = "Histogram of Residuals (Comparison)", breaks = 50, col = rgb(0, 0, 1, 0.25))
hist(res.new, breaks = 50, col = rgb(1, 0, 0, 0.25), add = TRUE)
#abline(v = 0, col = "red")
legend("topleft", legend = c("Homoskedastic", "Heteroskedastic"), col = c("blue", "pink"), lty = 1)
 

sigmai.mean = apply(omega.lambda, 1, mean)
sigmai.mean = 1/sqrt(sigmai.mean)
hist(drop(res.new)/sigmai.mean, breaks = 30)

post.lambdas = apply(lambda.save, 1, mean)

hist(post.lambdas)
```

